import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { MouseEventHandler } from "react";
import { PatientTrackerPage, TimelineFormData } from "../../components";
import {
  usePatientMutation,
  usePatientQuery,
  usePatientsQuery,
  useTimelineQuery,
} from "../../hooks";

const PatientDetailNextPage: NextPage = (props) => {
  const router = useRouter();
  const { id: patientId } = router.query;

  const patientsQuery = usePatientsQuery();
  const patientQuery = usePatientQuery(patientId as string);
  const { addPatient, updatePatient, deletePatient } = usePatientMutation();

  const { patients = [] } = patientsQuery.data ?? {};
  const { patient: selectedPatient } = patientQuery.data ?? {};

  const handleAddPatient = async (data: any) => {
    await addPatient(data);
    await patientsQuery.refetch();
  };

  const handleDeletePatient = async (data: any) => {
    await deletePatient(data);
    await patientsQuery.refetch();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PatientTrackerPage
        patients={patients}
        selectedPatient={selectedPatient}
        addPatient={handleAddPatient}
        deletePatient={handleDeletePatient}
        updatePatient={updatePatient}
        onTimelineDelete={function (id: string) {
          throw new Error("Function not implemented.");
        }}
        onTimelineSubmit={function (data: TimelineFormData) {
          throw new Error("Function not implemented.");
        }}
      />
    </div>
  );
};

export default PatientDetailNextPage;
