import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PatientTrackerPage, TimelineFormData } from "../components";
import { usePatientMutation, usePatientsQuery } from "../hooks";

const Home: NextPage = () => {
  const patientsQuery = usePatientsQuery();
  const { patients = [] } = patientsQuery.data ?? {};
  const { addPatient, updatePatient, deletePatient } = usePatientMutation();

  const handleAddPatient = async (data: any) => {
    await addPatient(data);
    await patientsQuery.refetch();
  };

  const handleDeletePatient = async (data: any) => {
    await deletePatient(data);
    await patientsQuery.refetch();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PatientTrackerPage
        patients={patients}
        selectedPatient={null}
        addPatient={handleAddPatient}
        deletePatient={handleDeletePatient}
        updatePatient={updatePatient}
        onTimelineDelete={function (id: string) {
          throw new Error("Function not implemented.");
        }}
        onTimelineSubmit={function (data: TimelineFormData) {
          throw new Error("Function not implemented.");
        }}
      />
    </div>
  );
};

export default Home;
